Added authentication to HTTP request
JakeWharton/sdk-artifact-sync pull request #3
Opened 2016-11-16 15:31 UTC by tkirshboim

The user/password combination used is extracted from the maven settings.xml file for the given repository ID.

This fixes #1

2016-11-17 17:57 UTC, JakeWharton requested changes
Looks good. Just some small tweak needed.

2016-11-17 17:57 UTC, JakeWharton commented on sdk-artifact-sync.py
> -
Tsk tsk this violates PEP 8! I see you're not using PyCharm for editing this file or it would yell at you!

2016-11-17 17:57 UTC, JakeWharton commented on sdk-artifact-sync.py
> +import xml.etree.ElementTree
Usually this gets aliased by adding `as ElementTree` so that you don't need to fully qualify it below

2016-11-17 17:57 UTC, JakeWharton commented on sdk-artifact-sync.py
> +mvn_settings = xml.etree.ElementTree.parse(os.environ['HOME'] + '/.m2/settings.xml').getroot()
This won't work cross-platform. You should use `os.path.expanduser('~')` to get the home directory and then `os.path.join` to append `.m2` and `settings.xml` to it.

2016-11-17 20:30 UTC, tkirshboim commented
Thanks for the feedback.
It's the first time I write Python so I assumed I'd be showing some bad
practice.
I'll do the changes you suggested.

On Thu, Nov 17, 2016, 6:57 PM Jake Wharton <notifications@github.com> wrote:

> *@JakeWharton* requested changes on this pull request.
>
> Looks good. Just some small tweak needed.
> ------------------------------
>
> In sdk-artifact-sync.py
> <https://github.com/JakeWharton/sdk-artifact-sync/pull/3#pullrequestreview-9080469>
> :
>
> > @@ -123,18 +134,18 @@
>  if verbose:
>      print
>
> -
>
> Tsk tsk this violates PEP 8! I see you're not using PyCharm for editing
> this file or it would yell at you!
> ------------------------------
>
> In sdk-artifact-sync.py
> <https://github.com/JakeWharton/sdk-artifact-sync/pull/3#pullrequestreview-9080469>
> :
>
> >  import os
>  import subprocess
>  import sys
>  import urllib2
> +import xml.etree.ElementTree
>
> Usually this gets aliased by adding as ElementTree so that you don't need
> to fully qualify it below
> ------------------------------
>
> In sdk-artifact-sync.py
> <https://github.com/JakeWharton/sdk-artifact-sync/pull/3#pullrequestreview-9080469>
> :
>
> > @@ -74,6 +76,15 @@
>  if verbose:
>      print 'Actual SDK m2repository folders:\n  %s' % '\n  '.join(sdk_m2_repos)
>
> +auth_base64 = ''
> +mvn_settings = xml.etree.ElementTree.parse(os.environ['HOME'] + '/.m2/settings.xml').getroot()
>
> This won't work cross-platform. You should use os.path.expanduser('~') to
> get the home directory and then os.path.join to append .m2 and
> settings.xml to it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/JakeWharton/sdk-artifact-sync/pull/3#pullrequestreview-9080469>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABohSsmrkpBs1KhP4Vwb4tc2NiorcC8Nks5q_JV7gaJpZM4K0AWk>
> .
>

2016-11-18 09:41 UTC, tkirshboim commented
@JakeWharton I've done the requested changes. Pinging for a second review.

2016-11-18 18:55 UTC, merged

2016-11-18 18:55 UTC, JakeWharton commented
Thanks!